# Create a new task file to use the simplified template:
# filepath: /home/user/ansible_homelab_kubernetes/standalone_control_plane/roles/elk_stack/tasks/kibana_simplified.yml
---
- name: Remove existing Kibana resources
  shell: |
    kubectl --kubeconfig={{ kubeconfig_path }} delete deployment kibana -n {{ elk_namespace }} || true
    kubectl --kubeconfig={{ kubeconfig_path }} delete configmap kibana-config -n {{ elk_namespace }} || true
    kubectl --kubeconfig={{ kubeconfig_path }} delete service kibana -n {{ elk_namespace }} || true
    kubectl --kubeconfig={{ kubeconfig_path }} delete ingressroute kibana -n {{ elk_namespace }} || true
  delegate_to: "{{ groups['utility'][0] }}"
  become: false
  changed_when: true

- name: Apply new Kibana deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    template: "{{ playbook_dir }}/roles/elk_stack/templates/kibana-simple.yaml.j2"
  delegate_to: "{{ groups['utility'][0] }}"
  become: false