- name: Setup K3s Control Plane
  hosts: k3s_control_plane
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install networking diagnostic utilities
      apt:
        name:
          - net-tools
          - netcat-openbsd
          - curl
          - traceroute
          - iproute2
          - iputils-ping
          - dnsutils
        state: present
        update_cache: yes
      become: true

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"

    - name: Install k3s control plane
      ansible.builtin.command: /tmp/k3s-install.sh
      environment:
        INSTALL_K3S_EXEC: --datastore-endpoint='sqlite:///var/lib/rancher/k3s/server.db'
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s service is enabled and started
      ansible.builtin.systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Wait for k3s to be up and running
      ansible.builtin.wait_for:
        port: 6443
        delay: 10

    - name: Get the node token from the control plane
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token
      changed_when: false

    - name: Store node token
      ansible.builtin.set_fact:
        k3s_token: "{{ node_token.stdout }}"

    - name: Display the node token
      ansible.builtin.debug:
        msg: Node token is {{ k3s_token }}
