- name: Cleanup Elastic Cloud on Kubernetes (ECK)
  hosts: utility
  gather_facts: true
  vars:
    kubeconfig_path: "{{ playbook_dir }}/fetched_tokens/k3s-kubeconfig"
    elastic_namespace: elastic
    operator_namespace: elastic-system

  tasks:
    - name: Display cleanup information
      ansible.builtin.debug:
        msg: Starting cleanup of ECK components from the cluster...

      # First remove Ingress and exposed services
    - name: Remove Elasticsearch and Kibana IngressRoutes
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: "{{ item }}"
            namespace: "{{ elastic_namespace }}"
      loop:
        - elasticsearch
        - kibana
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove Elasticsearch and Kibana Middlewares
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: "{{ item }}-strip-prefix"
            namespace: "{{ elastic_namespace }}"
      loop:
        - elasticsearch
        - kibana
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove TLS proxy services
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item }}-tls-proxy"
            namespace: "{{ elastic_namespace }}"
      loop:
        - elasticsearch
        - kibana
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove NodePort services
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item }}"
            namespace: "{{ elastic_namespace }}"
      loop:
        - elasticsearch-es-nodeport
        - kibana-kb-nodeport
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

      # Remove Kibana and Elasticsearch resources
    - name: Remove Kibana
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: kibana.k8s.elastic.co/v1
          kind: Kibana
          metadata:
            name: kibana
            namespace: "{{ elastic_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Wait for Kibana to be deleted
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} -n {{ elastic_namespace }} \
          get kibana 2>&1 | grep -c "No resources found" || true
      register: kibana_deleted
      until: kibana_deleted.stdout|int > 0 or kibana_deleted.rc != 0
      retries: 10
      delay: 10
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      changed_when: false
      ignore_errors: true

    - name: Remove Elasticsearch
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: elasticsearch
            namespace: "{{ elastic_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Wait for Elasticsearch to be deleted
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} -n {{ elastic_namespace }} \
          get elasticsearch 2>&1 | grep -c "No resources found" || true
      register: elasticsearch_deleted
      until: elasticsearch_deleted.stdout|int > 0 or elasticsearch_deleted.rc != 0
      retries: 12
      delay: 15
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      changed_when: false
      ignore_errors: true

    - name: Remove elastic namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ elastic_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true
      when: elasticsearch_deleted.stdout|int > 0 or elasticsearch_deleted.rc != 0

      # Remove the ECK operator
    - name: Remove ECK operator
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        src: https://download.elastic.co/downloads/eck/2.9.0/operator.yaml
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Wait for ECK operator to be deleted
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} -n {{ operator_namespace }} \
          get statefulset 2>&1 | grep -c "No resources found" || true
      register: operator_deleted
      until: operator_deleted.stdout|int > 0 or operator_deleted.rc != 0
      retries: 10
      delay: 10
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      changed_when: false
      ignore_errors: true

      # Remove the CRDs last
    - name: Remove ECK CRDs
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        src: https://download.elastic.co/downloads/eck/2.9.0/crds.yaml
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove operator namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ operator_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true
      when: operator_deleted.stdout|int > 0 or operator_deleted.rc != 0

      # Check for any leftover PVCs
    - name: Check for any leftover PVCs
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} \
          get pvc --all-namespaces | grep elasticsearch-data || true
      register: leftover_pvcs
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      changed_when: false
      ignore_errors: true

    - name: Display PVCs that might need manual cleanup
      ansible.builtin.debug:
        msg:
          - "The following PVCs related to Elasticsearch still exist and may need manual
            cleanup:"
          - "{{ leftover_pvcs.stdout_lines }}"
      when: leftover_pvcs.stdout != ""

    - name: Display cleanup completion message
      ansible.builtin.debug:
        msg:
          - ECK cleanup has completed.
          - "--------------------------------------"
          - "The following components have been removed:"
          - "- Elasticsearch and Kibana IngressRoutes"
          - "- Elasticsearch and Kibana Middlewares"
          - "- TLS proxy services"
          - "- NodePort services"
          - "- Kibana instances"
          - "- Elasticsearch instances"
          - "- ECK operator"
          - "- ECK CRDs"
          - "- Namespaces: {{ elastic_namespace }} and {{ operator_namespace }}"
          - "--------------------------------------"
          - "Note: If any of the components failed to delete, you may need to manually
            remove them."
          - "You can use the following commands to verify removal:"
          - kubectl get all -n {{ elastic_namespace }}
          - kubectl get all -n {{ operator_namespace }}
          - kubectl get crd | grep elastic
