- name: Cleanup ECK Operator and CRDs
  hosts: utility
  gather_facts: true
  vars:
    kubeconfig_path: "{{ playbook_dir }}/fetched_tokens/k3s-kubeconfig"
    elastic_namespace: elastic
    operator_namespace: elastic-system

  tasks:
    - name: Display cleanup information
      ansible.builtin.debug:
        msg: Starting cleanup of ECK operator components from the cluster...

      # Remove the ECK operator
    - name: Remove ECK operator
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        src: https://download.elastic.co/downloads/eck/2.9.0/operator.yaml
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Wait for ECK operator to be deleted
      ansible.builtin.shell: |
        kubectl --kubeconfig={{ kubeconfig_path }} -n {{ operator_namespace }} \
          get statefulset 2>&1 | grep -c "No resources found" || true
      register: operator_deleted
      until: operator_deleted.stdout|int > 0 or operator_deleted.rc != 0
      retries: 10
      delay: 10
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      changed_when: false
      ignore_errors: true

      # Remove the CRDs last
    - name: Remove ECK CRDs
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        src: https://download.elastic.co/downloads/eck/2.9.0/crds.yaml
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove elastic namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ elastic_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true

    - name: Remove operator namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ operator_namespace }}"
      delegate_to: "{{ groups['utility'][0] }}"
      become: false
      ignore_errors: true
      when: operator_deleted.stdout|int > 0 or operator_deleted.rc != 0

    - name: Display cleanup completion message
      ansible.builtin.debug:
        msg:
          - ECK operator cleanup has completed.
          - "--------------------------------------"
          - "The following components have been removed:"
          - "- ECK operator"
          - "- ECK CRDs"
          - "- Namespaces: {{ elastic_namespace }} and {{ operator_namespace }}"
          - "--------------------------------------"
          - "Note: If any of the components failed to delete, you may need to manually
            remove them."
          - "You can use the following commands to verify removal:"
          - kubectl get all -n {{ elastic_namespace }}
          - kubectl get all -n {{ operator_namespace }}
          - kubectl get crd | grep elastic
