- name: ECK Stack Verification
  hosts: utility
  gather_facts: false
  tasks:
    - name: Display verification start information
      ansible.builtin.debug:
        msg:
          - Starting ECK stack verification...
          - This will check the health of ECK operator, Elasticsearch, Kibana, and Ingress
            configuration.
          - "--------------------------------------"

- name: Verify ECK Operator
  import_playbook: verify_112_eck_operator.yml

- name: Verify Elasticsearch
  import_playbook: verify_114_eck_elasticsearch.yml

- name: Verify Kibana
  import_playbook: verify_116_eck_kibana.yml

- name: Show verification completion
  hosts: utility
  gather_facts: false
  tasks:
    - name: Display verification completion information
      ansible.builtin.debug:
        msg:
          - "--------------------------------------"
          - ECK stack verification completed successfully!
          - All components are working properly.
          - "--------------------------------------"
