---
- name: Create namespace for ECK operator
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
  delegate_to: "{{ groups['utility'][0] }}"
  become: false

- name: Deploy ECK CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: https://download.elastic.co/downloads/eck/{{ version }}/crds.yaml
  delegate_to: "{{ groups['utility'][0] }}"
  become: false

- name: Deploy ECK operator
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: https://download.elastic.co/downloads/eck/{{ version }}/operator.yaml
  delegate_to: "{{ groups['utility'][0] }}"
  become: false

- name: Wait for ECK operator to start (pause)
  pause:
    seconds: 30
  delegate_to: "{{ groups['utility'][0] }}"

- name: Check if ECK operator StatefulSet is ready
  shell: |
    kubectl --kubeconfig={{ kubeconfig }} -n {{ namespace }} get statefulset/elastic-operator -o jsonpath='{.status.readyReplicas}'
  register: operator_replicas
  until: operator_replicas.stdout | int > 0
  retries: 12
  delay: 10
  delegate_to: "{{ groups['utility'][0] }}"
  become: false
  changed_when: false
  ignore_errors: true

- name: Display ECK operator status
  debug:
    msg: "ECK operator has {{ operator_replicas.stdout | default('0') }} ready replicas"