---
- name: Install k3s on control-plane node
  hosts: k3s_control_plane
  become: yes
  roles:
    - k3s_control_plane

- name: Install k3s on worker nodes
  hosts: k3s_worker
  become: yes
  roles:
    - k3s_worker

