---
# roles/k3s_worker/tasks/firewall.yml

- name: Install UFW
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Enable UFW with deny default policy
  community.general.ufw:
    state: enabled
    policy: deny

- name: Open essential worker node ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'     # SSH
    - '10250'  # Kubelet
    - '10256'  # Kube-proxy health check

- name: Open network overlay ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop:
    - '8472'   # Flannel VXLAN
    - '51820'  # Wireguard (if used)

- name: Open NodePort range
  community.general.ufw:
    rule: allow
    port: '30000:32767'
    proto: tcp

- name: Configure UFW forwarding
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Allow internal network communication
  community.general.ufw:
    rule: allow
    src: '{{ internal_network_cidr }}'
  when: internal_network_cidr is defined
