---
# roles/k3s_worker/tasks/main.yml

- name: Ensure required packages are installed
  apt:
    pkg:
      - curl
      - wget
      - gpg
      - software-properties-common
      - apt-transport-https
    state: present
    update_cache: yes

- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Join k3s cluster
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="agent" \
    INSTALL_K3S_VERSION="{{ k3s_version | default('v1.28.5+k3s1') }}" \
    sh -
  when: not k3s_binary.stat.exists
  environment:
    K3S_URL: "https://{{ k3s_control_plane_endpoint }}:6443"
    K3S_TOKEN: "{{ k3s_cluster_token }}"

- name: Configure k3s agent node labels
  copy:
    dest: /etc/default/k3s
    content: |
      K3S_AGENT_ARGS="--node-label {{ worker_node_labels | default('') }}"
    mode: '0644'
  when: worker_node_labels is defined

- name: Ensure k3s-agent service is enabled and started
  systemd:
    name: k3s-agent
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for k3s agent to join cluster
  wait_for:
    path: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
    timeout: 300
    delay: 10
