---
- name: Pre-flight checks for k3s cluster
  hosts: all
  become: yes
  tasks:
    - name: Ensure system is up to date
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
    - name: Check if Python 3 is installed
      ansible.builtin.command: /usr/bin/python3 --version
      register: python3_check
      changed_when: false
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - curl
          - iptables
          - ufw
        state: present
      when: ansible_os_family == "Debian"
    - name: Check if nodes are reachable
      ansible.builtin.ping:
