---
# General settings
prometheus_namespace: monitoring
prometheus_release_name: prometheus
helm_operation_timeout: 600
update_helm_repo: true

# Prometheus configuration
prometheus_service_name: prometheus-operated
prometheus_port: 9090
prometheus_retention: 7d
prometheus_storage_size: 10Gi
prometheus_storage_class: standard

# Alertmanager configuration
alertmanager_enabled: true
alertmanager_replicas: 1

# Node exporter configuration
node_exporter_enabled: true

# Kube state metrics configuration
kube_state_metrics_enabled: true

# Grafana integration
grafana_enabled: true
grafana_admin_password: admin  # Should use Ansible vault in production
grafana_service_type: ClusterIP

# Custom values and dashboards configuration
prometheus_custom_values: false
prometheus_custom_dashboards: true

# Define values override for simpler configurations
prometheus_values_override:
  prometheus:
    prometheusSpec:
      retention: "{{ prometheus_retention }}"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "{{ prometheus_storage_class }}"
            resources:
              requests:
                storage: "{{ prometheus_storage_size }}"
  alertmanager:
    enabled: "{{ alertmanager_enabled }}"
    alertmanagerSpec:
      replicas: "{{ alertmanager_replicas }}"
  nodeExporter:
    enabled: "{{ node_exporter_enabled }}"
  kubeStateMetrics:
    enabled: "{{ kube_state_metrics_enabled }}"
  grafana:
    enabled: "{{ grafana_enabled }}"
    adminPassword: "{{ grafana_admin_password }}"
    service:
      type: "{{ grafana_service_type }}"

# Additional exporters to install separately if needed
prometheus_exporters: []
# Example:
# prometheus_exporters:
#   - name: redis-exporter
#     chart: prometheus-community/prometheus-redis-exporter
#     values:
#       serviceMonitor:
#         enabled: true
#       redis:
#         addr: redis:6379

# ServiceMonitor resources for custom application monitoring
prometheus_service_monitors: []
# Example:
# prometheus_service_monitors:
#   - apiVersion: monitoring.coreos.com/v1
#     kind: ServiceMonitor
#     metadata:
#       name: app-monitor
#       namespace: monitoring
#     spec:
#       selector:
#         matchLabels:
#           app: my-app
#       endpoints:
#         - port: web
#           interval: 30s
#           path: /metrics