---
# Default variables for the ELK stack role

# Namespace for the ELK stack
elk_namespace: "elk-stack"

# Deployment flags
deploy_elasticsearch: true
deploy_kibana: true
deploy_logstash: true  # Make sure this is true

# Default variables for ELK stack deployment
elasticsearch_cluster_name: "k3s-elk"
elasticsearch_protocol: "http"
elasticsearch_port: 9200
elasticsearch_extra_env_vars: []
elasticsearch_plugins: []
elasticsearch_init_containers: []

# Node configuration defaults
elasticsearch_replicas: 1
kibana_replicas: 1
logstash_replicas: 1

# Resource defaults
elasticsearch_heap_size: "1g"
elasticsearch_storage_size: "10Gi"

# Traefik settings
traefik_namespace: kube-system