---
# roles/k3s_control_plane/tasks/firewall.yml

- name: Install UFW (Uncomplicated Firewall)
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Open SSH port
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Open Kubernetes control plane ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '6443'   # Kubernetes API server
    - '2379'   # etcd client port
    - '2380'   # etcd peer port
    - '10250'  # Kubelet API
    - '10251'  # kube-scheduler
    - '10252'  # kube-controller-manager

- name: Open additional k3s required ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop:
    - '8472'   # Flannel VXLAN overlay network
    - '51820'  # Wireguard backend for Flannel (if used)

- name: Open NodePort range
  community.general.ufw:
    rule: allow
    port: '30000:32767'
    proto: tcp

- name: Allow internal network communication
  community.general.ufw:
    rule: allow
    src: '{{ internal_network_cidr }}'
  when: internal_network_cidr is defined

- name: Allow forwarding
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify: Restart UFW

- name: Configure UFW before.rules for NAT and IP masquerading
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
      # NAT table for IP masquerading
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s {{ internal_network_cidr }} -j MASQUERADE
      COMMIT
    marker: "# {mark} UFW NAT CONFIGURATION"
    insertbefore: "# Don't delete these required lines"
  when: internal_network_cidr is defined
