---
# Set up Traefik ingress for Grafana
- name: Create Grafana IngressRoute
  template:
    src: grafana-ingressroute.yaml.j2
    dest: "{{ playbook_dir }}/fetched_tokens/grafana-ingressroute.yaml"
    mode: '0600'
  delegate_to: localhost
  become: false
  
- name: Apply Grafana IngressRoute
  command: >
    kubectl --kubeconfig={{ kubeconfig_path }}
    apply -f {{ playbook_dir }}/fetched_tokens/grafana-ingressroute.yaml
  register: ingressroute_applied
  changed_when: ingressroute_applied.rc == 0
  delegate_to: localhost
  become: false

# Create compatibility Ingress for non-CRD controllers
- name: Create Grafana standard Ingress
  template:
    src: grafana-ingress.yaml.j2
    dest: "{{ playbook_dir }}/fetched_tokens/grafana-ingress.yaml"
    mode: '0600'
  delegate_to: localhost
  become: false
  
- name: Apply Grafana standard Ingress
  command: >
    kubectl --kubeconfig={{ kubeconfig_path }}
    apply -f {{ playbook_dir }}/fetched_tokens/grafana-ingress.yaml
  register: ingress_applied
  changed_when: ingress_applied.rc == 0
  delegate_to: localhost
  become: false

# Update Grafana configuration for subpath support
- name: Create ConfigMap for Grafana ini settings
  template:
    src: grafana-settings-configmap.yaml.j2
    dest: "{{ playbook_dir }}/fetched_tokens/grafana-settings-configmap.yaml"
    mode: '0600'
  delegate_to: localhost
  become: false
  when: grafana_subpath_enabled | default(true)
  
- name: Apply Grafana settings ConfigMap
  command: >
    kubectl --kubeconfig={{ kubeconfig_path }}
    apply -f {{ playbook_dir }}/fetched_tokens/grafana-settings-configmap.yaml
  register: configmap_applied
  changed_when: configmap_applied.rc == 0
  delegate_to: localhost
  become: false
  when: grafana_subpath_enabled | default(true)

# Restart Grafana deployment if config changed
- name: Restart Grafana deployment if config changed
  command: >
    kubectl --kubeconfig={{ kubeconfig_path }}
    -n {{ grafana_namespace }}
    rollout restart deployment {{ grafana_release_name }}
  when: configmap_applied is changed
  delegate_to: localhost
  become: false

# Get Grafana admin password
- name: Get Grafana admin password
  shell: >
    kubectl --kubeconfig={{ kubeconfig_path }} 
    get secret -n {{ grafana_namespace }} {{ grafana_release_name }} -o jsonpath="{.data.admin-password}" | 
    base64 --decode
  register: grafana_password
  changed_when: false
  no_log: true
  delegate_to: localhost
  become: false

# Display Grafana access information
- name: Display Grafana access information via Traefik
  debug:
    msg:
      - "Grafana Traefik Ingress has been successfully configured!"
      - "---------------------------------------------" 
      - "Access Grafana at:"
      - "- Host-based: http://{{ grafana_ingress_host }}"
      - "- Path-based: http://{{ ansible_host }}:{{ traefik_port | default('80') }}/grafana/"
      - "Username: admin"
      - "Password: {{ grafana_password.stdout }}"
      - "---------------------------------------------"
  delegate_to: localhost
  become: false