# Step 5: Elastic Stack
- name: Setup Elastic Cloud on Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: elastic_operator
      tags: [elastic, eck, operator]
    - role: elasticsearch
      tags: [elastic, eck, elasticsearch]
    - role: kibana
      tags: [elastic, eck, kibana]
    - role: filebeat
      tags: [elastic, eck, filebeat]
