- name: Setup K3s
  import_playbook: k3s.yml
  tags: [k3s, control_plane, workers]

- name: Configure NFS Storage
  import_playbook: nfs.yml
  tags: [storage, nfs, nfs-server, nfs-clients, nfs-provisioner]

- name: Configure Storage Infrastructure
  import_playbook: storage.yml
  tags: [storage, minio]

- name: Deploy Network Infrastructure
  import_playbook: networking.yml
  tags: [network, ingress, traefik, dashboard]

- name: Deploy Monitoring Stack
  import_playbook: prometheus_grafana.yml
  tags: [monitoring, prometheus, grafana]

- name: Grafana dashboards
  import_playbook: install_100_monitoring.yml
  tags: [monitoring, extras]

- name: Elastic Stack
  import_playbook: install_110_eck.yml
  tags: [elastic, eck]

- name: Deploy MLflow
  import_playbook: install_120_mlflow.yml
  tags: [ml, mlflow]

- name: Deploy Argo Workflows
  import_playbook: install_130_argo_workflows.yml
  tags: [workflow, argowf]

- name: Deploy Seldon
  import_playbook: install_150_seldon.yml
  tags: [ml, seldon]

- name: Display deployment complete banner
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display deployment complete banner
      ansible.builtin.debug:
        msg:
          - "*******************************************************************"
          - "*             KUBERNETES HOMELAB DEPLOYMENT COMPLETE              *"
          - "*******************************************************************"
          - ""
          - "Access your services at:"
          - "- Kubernetes Dashboard: https://<control-plane-ip>:{{ lookup('env', 'K8S_DASHBOARD_PORT')
            | default('30443') }}"
          - "- Grafana: http://<control-plane-ip>:{{ lookup('env', 'TRAEFIK_NODE_PORT')
            | default('32080') }}/grafana"
          - "- Prometheus: http://<control-plane-ip>:{{ lookup('env', 'TRAEFIK_NODE_PORT')
            | default('32080') }}/prometheus"
          - "- Kibana: https://<control-plane-ip>:{{ lookup('env', 'KIBANA_NODE_PORT')
            | default('30056') }}/kibana"
          - "- MLflow: http://<control-plane-ip>:{{ lookup('env', 'TRAEFIK_NODE_PORT')
            | default('32080') }}/mlflow"
          - "- MinIO Console: http://<control-plane-ip>:{{ lookup('env', 'MINIO_CONSOLE_PORT')
            | default('30090') }}"
          - "- Seldon Core API: http://<control-plane-ip>:{{ lookup('env', 'SELDON_NODE_PORT')
            | default('30150') }}/seldon/"
          - ""
          - See documentation for credentials and further instructions.
