# Setup K3s Cluster
- name: Configure K3s Control Plane
  hosts: k3s_control_plane
  become: true
  gather_facts: true
  vars:
    k3s_state: present  # Options: present, absent
  roles:
    - role: k3s_control_plane
      tags: [k3s, control_plane]

- name: Fetch kubeconfig to localhost
  hosts: localhost
  gather_facts: false
  vars:
    k3s_state: present  # Options: present, absent
  roles:
    - role: fetch_kubeconfig
      tags: [k3s, kubeconfig]
      when: k3s_state == 'present'

- name: Configure K3s Worker Nodes
  hosts: k3s_workers
  become: true
  gather_facts: true
  vars:
    k3s_state: present  # Options: present, absent
  roles:
    - role: k3s_workers
      tags: [k3s, workers]
