---
- name: Deploy K3s Control Plane
  hosts: k3s_control_plane
  become: true
  roles:
    - k3s_control_plane

- name: Deploy K3s Worker Nodes
  hosts: k3s_workers
  become: true
  roles:
    - k3s_workers
