---
# Step 6: ML Infrastructure
- name: Setup Machine Learning Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: mlflow
      tags: [ml, mlflow]
    - role: seldon
      tags: [ml, seldon]
