---
# MLOps platform and demo applications

# First, prepare Kubernetes access
- name: Prepare Kubernetes access
  hosts: localhost
  gather_facts: false

# Deploy ArgoCD (if you have an ArgoCD role)
- name: Deploy ArgoCD
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - argo_cd

# Deploy Argo Workflows (if you have an Argo Workflows role)
- name: Deploy Argo Workflows
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - argo_workflows

# Deploy MLOps Demo Application
- name: Deploy MLOps Demo Application
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - mlops_demo_app
