---
# Monitoring stack deployment
- name: Deploy Monitoring Stack
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    prometheus_crd_base_url: "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd"
  roles:
    # - role: prometheus_operator  # <-- Add this role if you have it
    #   tags: [monitoring, prometheus]
    - role: kube_state_metrics   # <-- Run after prometheus operator
      tags: [monitoring, kube-state-metrics]
    - role: prometheus
      tags: [monitoring, prometheus]
    - role: grafana
      tags: [monitoring, grafana]
    - role: metrics_server
    - role: node_exporter
