---
- name: Install Monitoring Stack
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/all/common.yml

  vars:
    prometheus_crd_base_url: "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd"

  roles:
    - prometheus
    - grafana
    - metrics_server
    - kube_state_metrics
    - node_exporter
