# Then proceed with NFS server setup
- name: Install and configure NFS server
  hosts: nfs_server
  become: true
  roles:
    - nfs_server

- name: Install and configure NFS clients
  hosts: nfs_clients
  become: true
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - nfs_clients

- name: Deploy NFS provisioner on Kubernetes
  hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - nfs_provisioner
