---
# Storage infrastructure playbook - combines NFS and Object Storage solutions

# First, prepare Kubernetes access
- name: Prepare Kubernetes access
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml

# Deploy NFS storage provisioner
- name: Deploy NFS Storage
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - nfs_provisioner

# Deploy MinIO Object Storage
- name: Deploy MinIO Object Storage
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all/common.yml
  roles:
    - minio
