---
# Storage infrastructure playbook - combines NFS and Object Storage solutions

- name: Configure NFS Server
  hosts: nfs_server
  gather_facts: true
  become: true
  roles:
    - role: nfs_server
      tags: [storage, nfs, nfs-server]

- name: Configure NFS Clients
  hosts: k3s_control_plane:k3s_workers
  gather_facts: true
  become: true
  roles:
    - role: nfs_clients
      tags: [storage, nfs, nfs-clients]

- name: Setup Kubernetes Storage Components
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: nfs_provisioner
      tags: [storage, nfs, nfs-provisioner]
    - role: minio
      tags: [storage, minio]
